version: '2'

services:

    apps:
        image: tianon/true
        volumes:
            - ../:/var/www

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - apps
        volumes:
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "8000:80"
            - "443:443"
        mem_limit: 100M
        links:
            - php-fpm

    php-fpm:
        build:
            context: ./php-fpm
        volumes_from:
            - apps
        expose:
            - "9000"
        mem_limit: 200M
        links:
            - mysql

    mysql:
        build:
            context: ./mysql
        volumes:
            - ./db/:/db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        mem_limit: 200M
